### ISSUE TITLE
结构体或字符数组中的字符串访问是否可以统一

### ISSUE THREAD

**Issue by username13107** [amimo/goron#11]
结构体或字符数组中的字符串解密是否可以和常规字符串解密接口统一? 目前的实现把这两种情况单独暴露出来处理, 容易识别.

另外, 各个常规字符串的解密接口也可以统一用同一个吧, 目前的实现产生了很多冗余代码.

谢谢

**Comment by amimo** [comment]
> 结构体或字符数组中的字符串解密是否可以和常规字符串解密接口统一? 目前的实现把这两种情况单独暴露出来处理, 容易识别.

这个不太明白.

> 另外, 各个常规字符串的解密接口也可以统一用同一个吧, 目前的实现产生了很多冗余代码.

不使用统一解密函数,而是一个字符串一个解密函数,是为了避免破解者通过inline hook解密函数找到敏感字符串.

**Comment by username13107** [comment]
> > 结构体或字符数组中的字符串解密是否可以和常规字符串解密接口统一? 目前的实现把这两种情况单独暴露出来处理, 容易识别.
> 
> 这个不太明白.
> > 另外, 各个常规字符串的解密接口也可以统一用同一个吧, 目前的实现产生了很多冗余代码.
> 
> 不使用统一解密函数,而是一个字符串一个解密函数,是为了避免破解者通过inline hook解密函数找到敏感字符串.

谢谢回复, 我对于这两个问题的理解是相关联的. 我的想法是, 对于结构体、字符串数组、常量字符串都使用统一的解密函数, 然后做inline.

**Comment by amimo** [comment]
这个之前@qtfreet00也有提过,你可以参考[这个实现](https://github.com/amimo/goron/issues/3#issuecomment-542482188).

**Comment by username13107** [comment]
嗯,我看过这个issue. 但是里面只涉及到了inline, 对于结构体、字符串数组这块没有提到. 不知道你对将结构体、字符串数组和常量字符串类似处理这个问题怎么看呢? 
是否可以考虑在访问每个结构体变量时才将需要访问的还原呢? 而不是现在把整个结构体或数组还原.
谢谢🙏

**Comment by amimo** [comment]
> 不知道你对将结构体、字符串数组和常量字符串类似处理这个问题怎么看呢?

我还是不太明白你这个类似处理是什么处理?

> 是否可以考虑在访问每个结构体变量时才将需要访问的还原呢? 而不是现在把整个结构体或数组还原.

这个想法是不错,但很难实现.比如JNINativeMethod数组,他最终会在安卓中使用,这种情况我们只能整个数组解密好,然后使用解密好的数据调用系统API.

**Comment by username13107** [comment]
> > 不知道你对将结构体、字符串数组和常量字符串类似处理这个问题怎么看呢?
> 
> 我还是不太明白你这个类似处理是什么处理?

可能我说的太绕了, 我说的类似处理就是指不要整体还原.

> > 是否可以考虑在访问每个结构体变量时才将需要访问的还原呢? 而不是现在把整个结构体或数组还原.
> 
> 这个想法是不错,但很难实现.比如JNINativeMethod数组,他最终会在安卓中使用,这种情况我们只能整个数组解密好,然后使用解密好的数据调用系统API.

这个确实是我没有想到的, 确实如@qtfree0中所言, 字符串的使用场景复杂, 需要多测试.🙏

**Comment by amimo** [comment]
> 可能我说的太绕了, 我说的类似处理就是指不要整体还原.

目前结构体和数组整体还原是简单可靠的实现
