### ISSUE TITLE
how to protect target running at aarch64(arm64)?

### ISSUE THREAD

**Issue by JunfengJia** [amimo/goron#12]

**Comment by amimo** [comment]
your mean is to obfuscate arm64 code of an Android App or iOS?

**Comment by JunfengJia** [comment]
I like to obfuscate my application running at arm64 platform like raspberrypi64.

**Comment by amimo** [comment]
this article might be helpful. [Using Clang as a cross compiler for Raspberry Pi](https://solarianprogrammer.com/2019/05/04/clang-cross-compiler-for-raspberry-pi/)
