### ISSUE TITLE
arm64e

### ISSUE THREAD

**Issue by devsthing** [amimo/goron#13]
不支持编译arm64e？

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by amimo** [comment]
混淆是在ir做的,理论上所有后端都支持.

**Comment by littlebro-me** [comment]
看编译错误。去掉arm64e ，可以编译。clang-7: error: invalid arch name '-arch arm64e'
