### ISSUE TITLE
混淆是在ir做的,理论上所有后端都支持.

### ISSUE THREAD

**Issue by littlebro-me** [amimo/goron#14]
混淆是在ir做的,理论上所有后端都支持.

_Originally posted by @amimo in https://github.com/amimo/goron/issues/13#issuecomment-552266423_

看编译错误。去掉arm64e ，可以编译。clang-7: error: invalid arch name '-arch arm64e'

**Comment by amimo** [comment]
这个跟混淆没有关系.你先系统自带的clang测试下你的命令,没问题再使用goron混淆.下面这个命令你可以参考下.
```sh
clang  -S -target arm64e-linux-gnueabi t.c
```
