### ISSUE TITLE
如何编译windows能用的goron？

### ISSUE THREAD

**Issue by nyydwr** [amimo/goron#15]
你好，请问如何编译windows能用的goron？
我尝试按照互联网上编译ollvm的教程来编译goron，没成功。

**Comment by amimo** [comment]
我没有在windows上编译过.你看下这个官方文档有没有帮助[Getting Started with the LLVM System using Microsoft Visual Studio](https://llvm.org/docs/GettingStartedVS.html)

**Comment by nyydwr** [comment]
我尝试多次，按照ollvm的说明，生成clang++.exe、clang.exe、clang-format.exe这3个文件才算编译成功。
goron-llvm-9.0.0用Visual Studio 2019编译，失败二十几个，且没有生成clang++.exe、clang.exe、clang-format.exe。
goron-llvm-7.1.0用Visual Studio 2019编译，生成: 成功 350 个，失败 31 个，最新 0 个，跳过 0 个。生成clang-format.exe，没有clang++.exe、clang.exe。

大佬，有空，可以解决一下windows上编译问题吗？

**Comment by amimo** [comment]
官方的llvm工具链你能编译出来吗?代码应该是没有问题的,@qtfreet00这位大佬之前给我发过一个windows的样本

**Comment by nyydwr** [comment]
我用MinGW可以编译出来，可能是Visual Studio 2019我没配置好。

运行demo，报错
goron-llvm-7.1.0\build\bin>clang.exe -mllvm -irobf -mllvm --irobf-indbr demo.c
Cannot open /dev/randomCannot open /dev/randomCannot open /dev/randomCannot open /dev/randomCannot open /dev/randomCannot open /dev/random

**Comment by nyydwr** [comment]
我搜索了一下，有一篇文章 https://www.cnblogs.com/suanguade/p/10913303.html
但goron-llvm-7.1.0\llvm\lib\Transforms\Obfuscation\CryptoUtils.cpp和他的情况不一致，请问，该如何解决这个报错？

**Comment by amimo** [comment]
我搜索到了@qtfreet00大佬的这个提交[修复windows编译](https://github.com/qtfreet00/llvm-obfuscator/commit/11eb34405bb8f0ee0946c19a45b329d0ecf95e07),你可以把他仓库里面的对应文件覆盖过来.

**Comment by nyydwr** [comment]
好的，感谢，我试试

**Comment by nyydwr** [comment]
又尝试用VS2019编译，还是失败，可能VS就不能编译goron。

windows编译goron步骤：
0.按照qtfreet00大佬的提交修复windows编译
1.安装cmake和MinGW-64，并将两个软件的bin目录加入环境变量
cd goron
mkdir build
cd build
cmake -G "MinGW Makefiles" --enable-optimized --enable-targets=host-only -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_PROJECTS=clang ../llvm
mingw32-make -j10

**Comment by tzf-omkey** [comment]
@nyydwr  你好,请问您cmake和MinGW的版本分别是?我按照这种方式编译在47的地方因为CryptoUtils.cpp而出错.
请问您的CryptoUtils中是怎么根据qtfreet00大佬的改的.
