### ISSUE TITLE
Support for LLVM 10.0

### ISSUE THREAD

**Issue by sohsatoh** [amimo/goron#17]
Hi,
LLVM v10.0 has been released on their repo.

Could you port goron to ver 10.0?

https://github.com/llvm/llvm-project/tree/release/10.x

**Comment by amimo** [comment]
I will port it next month, after the Chinese New Year.

**Comment by sohsatoh** [comment]
Thank you so much:)

**Comment by amimo** [comment]
try the llvm-10.x-porting branch

**Comment by xmhwws** [comment]
> try the llvm-10.x-porting branch

编译结果：[ 98%] Built target obj.clangAST
mingw32-make: *** [Makefile:168: all] Error 2

相关信息：
[ 98%] Building CXX object tools/clang/lib/StaticAnalyzer/Checkers/CMakeFiles/obj.clangStaticAnalyzerCheckers.dir/UninitializedObject/UninitializedPointee.cpp.obj
E:\goron\llvm\tools\llvm-ar\llvm-ar.cpp: In function 'bool comparePaths(llvm::StringRef, llvm::StringRef)':
Scanning dependencies of target llvm-ltoE:\goron\llvm\tools\llvm-ar\llvm-ar.cpp:524:10:
 error: 'CompareStringOrdinal' was not declared in this scope
   return CompareStringOrdinal(WPath1.data(), WPath1.size(), WPath2.data(),
          ^~~~~~~~~~~~~~~~~~~~
E:\goron\llvm\tools\llvm-ar\llvm-ar.cpp:524:10: note: suggested alternative: 'CompareStringA'
   return CompareStringOrdinal(WPath1.data(), WPath1.size(), WPath2.data(),
          ^~~~~~~~~~~~~~~~~~~~
          CompareStringA
[ 98%] Building CXX object tools/llvm-lto/CMakeFiles/llvm-lto.dir/llvm-lto.cpp.obj
[ 98%] Built target llvm-objcopy
[ 98%] Building CXX object tools/clang/lib/StaticAnalyzer/Checkers/CMakeFiles/obj.clangStaticAnalyzerCheckers.dir/UnixAPIChecker.cpp.obj
[ 98%] Building CXX object tools/clang/lib/AST/CMakeFiles/obj.clangAST.dir/RecordLayoutBuilder.cpp.obj
mingw32-make[2]: *** [tools\llvm-ar\CMakeFiles\llvm-ar.dir\build.make:80: tools/llvm-ar/CMakeFiles/llvm-ar.dir/llvm-ar.cpp.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:25197: tools/llvm-ar/CMakeFiles/llvm-ar.dir/all] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....

**Comment by amimo** [comment]
官方的clang你编译过了吗?我只在Linux下测试过.

**Comment by xmhwws** [comment]
> 官方的clang你编译过了吗?我只在Linux下测试过.

我在windows10上编译的。
我之前编译过goron-9.0.0，没有问题，正常使用，所有配置环境没改变。

**Comment by amimo** [comment]
你先编译个官方的.看起来不像goron的问题.

**Comment by xmhwws** [comment]
我将尝试编译最新版
https://github.com/llvm/llvm-project/tree/release/10.x
大约1小时左右

编译完了，官方也有这个问题，不是goron的问题。

**Comment by qtfreet00** [comment]
加入windows宏即可

**Comment by qtfreet00** [comment]
https://github.com/amimo/goron/blob/29ee9fbf34d9138eb9097214946b2248acfba9a7/llvm/tools/llvm-ar/llvm-ar.cpp#L47

下加入#define WINVER 0x0601

**Comment by sohsatoh** [comment]
Thanks:) I will test it.
Anyway, could you try porting goron to support arm64e?
https://github.com/apple/llvm-project/pull/14
