### ISSUE TITLE
一个函数属性问题

### ISSUE THREAD

**Issue by hexstr** [amimo/goron#19]
如果没理解错的话，[这里](https://github.com/amimo/goron/blob/e943a8a78325632df64988e05d66ad5fa0e0c6f6/llvm/lib/Transforms/Obfuscation/Flattening.cpp#L59)好像也要改成`cff`，不然关闭某个函数的控制流平坦化就要用`nofla`而不是`nocff`了
我修改之后重新编译了一下好像是这样

**Comment by amimo** [comment]
是的,影响不大,先这么用吧,需要改的分支太多了.
