### ISSUE TITLE
能否考虑加上一些随机的因素，每次生成的跳转都不一样

### ISSUE THREAD

**Issue by ZhLinda** [amimo/goron#2]
能否考虑加上一些随机的因素，每次生成的跳转都不一样？

**Comment by amimo** [comment]
跳转不一样指的什么?
当前实现有一些随机因素.比如间接跳转混淆的跳转表,混淆用的key是随机的,里面基本块顺序也是随机打乱了.

**Comment by ZhLinda** [comment]
谢谢解答
