### ISSUE TITLE
LLVM源

### ISSUE THREAD

**Issue by ghost** [amimo/goron#20]
LLVM 9.0.8svn版本和谷歌ndk内置的llvm版本似乎是不一样的, 用llvm官方源和ndk配套是不是可能会有兼容性问题?
https://android.googlesource.com/toolchain/llvm-project

**Comment by amimo** [comment]
应该不会的.担心有问题的话可以这么操作:
把需要混淆的代码单独编译成静态库,在项目中使用这个静态库,这样就避免替换官方工具链.

**Comment by ghost** [comment]
> 应该不会的.担心有问题的话可以这么操作:
> 把需要混淆的代码单独编译成静态库,在项目中使用这个静态库,这样就避免替换官方工具链.

好的, 另外总体而言, goron和hikari哪个的混淆强度大? 不过hikari开源版最高支持llvm8

**Comment by amimo** [comment]
我的.goron混淆是过程相关的.反混淆一个函数,需要找到他的一个调用者,但函数调用点也被混淆了.
hikari字符串混淆很容易被静态patch,我这个要更困难些.

**Comment by ghost** [comment]
> 我的.goron混淆是过程相关的.反混淆一个函数,需要找到他的一个调用者,但函数调用点也被混淆了.
> hikari字符串混淆很容易被静态patch,我这个要更困难些.

Nice! hikari开启间接跳转在android上会crash, 我试试goron.
另外, goron对于反trace有做什么么, 感觉能trace就能反混淆, 或者说这是上层代码需要考虑的事情, 比如anti-unicorn啥的

**Comment by amimo** [comment]
编译器crash还是编译出来的二进制crash,后者可以甩锅llvm。
反trace没有研究过.
