### ISSUE TITLE
如何控制while循环的层数

### ISSUE THREAD

**Issue by ghost** [amimo/goron#23]
谢谢

**Comment by amimo** [comment]
能否具体点?

**Comment by ghost** [comment]
现在好像只有2层吧，能不能添加多层呢

**Comment by amimo** [comment]
这里的while循环指的什么?代码经goron混淆之后之后,ida里面是看不到循环的,包括最外层的cff的while大循环.

**Comment by ghost** [comment]
goron有添加while循环么

**Comment by amimo** [comment]
开启流程平坦混淆会有一个大while循环.

**Comment by ghost** [comment]
只有一层么

**Comment by ghost** [comment]
unsigned int __fastcall sub_9FC4(int a1, int a2)
{
  unsigned int v2; // r7
  int v3; // r9
  unsigned int result; // r0
  signed int v5; // r5
  unsigned int v6; // r0
  int v7; // [sp+4h] [bp-28h]

  v3 = a1;
  result = (unsigned __int8)byte_26F0A;
  v5 = -1201391435;
  v7 = (unsigned __int8)byte_26F0A;
  do
  {
    while ( 1 )
    {
      while ( v5 >= 1551167504 )
      {
        if ( v5 >= 2030350507 )
        {
          if ( v5 == 2030350507 )
          {
            result = (unsigned int)&byte_26F0A;
            byte_26F0A = 1;
            v5 = -1072465114;
          }
        }
        else if ( v5 == 1551167504 )
        {
          *(_BYTE *)(v3 + v2) = *(_BYTE *)(a2 +

**Comment by amimo** [comment]
这个不是goron混淆出来的代码吧.这个while是反编译器识别的,实际上只有一个循环.你可以用binary ninja的反编译器看看.
