### ISSUE TITLE
间接跳转导致so闪退

### ISSUE THREAD

**Issue by ghost** [amimo/goron#25]
没加固之前不会闪退，
如何定位到什么原因引起的

**Comment by ghost** [comment]
-icall选项

**Comment by ghost** [comment]
ub_17E80                               ; DATA XREF: .data:0002676C↓o
.text:00017E80
.text:00017E80 var_10          = -0x10
.text:00017E80
.text:00017E80 ; __unwind {
.text:00017E80                 PUSH            {R4-R7,LR}
.text:00017E82                 ADD             R7, SP, #0xC
.text:00017E84                 STR.W           R8, [SP,#0xC+var_10]!
.text:00017E88                 LDR             R5, =(off_26E10 - 0x17E92)
.text:00017E8A                 MOV             R4, R3
.text:00017E8C                 LDR             R1, =0x44943360
.text:00017E8E                 ADD             R5, PC  ; off_26E10
.text:00017E90                 LDR             R6, =0xEF1801F8
.text:00017E92                 LDR             R0, [R5]
.text:00017E94                 MOV             R8, R1
.text:00017E96                 LDR             R0, [R0,R1]
.text:00017E98                 ADD             R0, R6
.text:00017E9A                 BLX             R0      ; sub_9C00
.text:00017E9A ; End of function sub_17E80

最后一句BLX             R0      ; sub_9C00，跳转的位置不是原代码要跳转到的目标函数，导致闪退。
这里面的sub_9C00是假函数么

**Comment by amimo** [comment]
所有函数都有问题还是只有这一个函数有问题?

**Comment by ghost** [comment]
在这个地方crash的，其他函数暂时没有发现有问题，多次在这里crash，app直接退出。

**Comment by amimo** [comment]
还是偶发的?
