### ISSUE TITLE
求帮助

### ISSUE THREAD

**Issue by jianfeng6** [amimo/goron#36]
![Screenshot_2021-10-18-21-53-48-579_com aide uj](https://user-images.githubusercontent.com/71310844/138566817-3a09267c-8e70-4861-99ee-6b92156abf27.jpg)
![Screenshot_2021-10-19-05-11-21-535_com aide uj](https://user-images.githubusercontent.com/71310844/138566835-c8280d9c-a721-4448-80d9-9c7b6b415582.jpg)
![Screenshot_2021-10-18-21-53-48-579_com aide uj](https://user-images.githubusercontent.com/71310844/138566838-6375b4f7-ae77-4a6f-aa23-c5ca9f490945.jpg)
![124598](https://user-images.githubusercontent.com/71310844/138566840-8b6cccd2-d653-4af0-aa8e-ac05458d6971.jpg)
![2021-10-24 01-41-23](https://user-images.githubusercontent.com/71310844/138566841-098a15c9-c056-4119-bbb1-c212ab6662d5.jpg)
clang++这个什么同问题windows/linux/aarch64/电脑手机都试过了。都是这个问题。求大佬给解决方案我是小白小白

**Comment by AReverso** [comment]
好兄弟解决了吗，我能编译出来 但是混淆没效果 你咋样
