### ISSUE TITLE
我的adnroid工程x86模拟器中稳定crash

### ISSUE THREAD

**Issue by cjycjw** [amimo/goron#37]
方便留一个联系方式吗？可以提供demo探讨一下！

**Comment by amimo** [comment]
试试这个提交 https://github.com/amimo/goron/tree/fix-cc

**Comment by cjycjw** [comment]
> 试试这个提交 https://github.com/amimo/goron/tree/fix-cc

好的，我这边重新编译一下试一下！

**Comment by cjycjw** [comment]
> 试试这个提交 https://github.com/amimo/goron/tree/fix-cc

确实可以了
