### ISSUE TITLE
不能编译Bitcode的bc文件

### ISSUE THREAD

**Issue by HuaZao** [amimo/goron#5]
**使用Hikari**
`clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs -fobjc-arc -c  DomainManager.bc -o DomainManagerOb.o`

`warning: overriding the module target triple with arm64-apple-ios5.0.0 [-Woverride-module]
std::mt19937_64 seeded with current timestamp: 1571280669417`
`Doing Post-Run Cleanup`
`Hikari Out`

`1 warning generated.`

**使用goron**
`clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs -fobjc-arc -c DomainManager.bc -o DomainManagerOb.o`

`error: Invalid record`
`1 error generated.`

没有使用任何Pass,开启了也是一样的结果

**Comment by amimo** [comment]
这个bc是用goron生成的吗?我猜测可能是bc不兼容.

**Comment by HuaZao** [comment]
@amimo  是用Xcode自带的编译器生成的,Hikari编译没问题, goron不行

**Comment by amimo** [comment]
clang --version 看看,可能是版本不一样.goron现在是7.1.0,还没有适配高版本

**Comment by HuaZao** [comment]
Hikari  -> clang version 8.0.0

**Comment by amimo** [comment]
等我适配好8之后你再试试吧

**Comment by HuaZao** [comment]
@amimo 好~

**Comment by amimo** [comment]
@HuaZao 你用试试[llvm-8.0.1](6512cd1569533958e134334d9b082592cd6f0794)

**Comment by HuaZao** [comment]
@amimo 非常感谢! llvm-8.0.1分支 测试正常
